// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[room]/[name]/index.tsx";
import * as $1 from "./routes/_404.ts";
import * as $2 from "./routes/_middleware.ts";
import * as $$0 from "./islands/DeathMessage.tsx";
import * as $$1 from "./islands/Display.tsx";
import * as $$2 from "./islands/JoinMessage.tsx";
import * as $$3 from "./islands/LeftMessage.tsx";
import * as $$4 from "./islands/SpawnMessage.tsx";
import * as $$5 from "./islands/UserMessage.tsx";

const manifest = {
  routes: {
    "./routes/[room]/[name]/index.tsx": $0,
    "./routes/_404.ts": $1,
    "./routes/_middleware.ts": $2,
  },
  islands: {
    "./islands/DeathMessage.tsx": $$0,
    "./islands/Display.tsx": $$1,
    "./islands/JoinMessage.tsx": $$2,
    "./islands/LeftMessage.tsx": $$3,
    "./islands/SpawnMessage.tsx": $$4,
    "./islands/UserMessage.tsx": $$5,
  },
  baseUrl: import.meta.url,
};

export default manifest;
